BASE_URL = 'https://apis.roblox.com'
VERSION_ONE = 'v1'
VERSION_TWO = 'v2'

BASE_VERSION_ONE_ASSETS = f'{BASE_URL}/universes/{VERSION_ONE}'
BASE_VERSION_ONE_DATASTORES = f'{BASE_URL}/universes/{VERSION_ONE}'
BASE_VERSION_ONE_MESSAGING = f'{BASE_URL}/messaging-service/{VERSION_ONE}'
BASE_VERSION_ONE_UNIVERSES = f'{BASE_URL}/universes/{VERSION_ONE}'

BASE_VERSION_TWO = f'{BASE_URL}/cloud/{VERSION_TWO}'

VERSION_LOOKUP = {
    BASE_VERSION_ONE_ASSETS: VERSION_ONE,
    BASE_VERSION_ONE_DATASTORES: VERSION_ONE,
    BASE_VERSION_ONE_MESSAGING: VERSION_ONE,
    BASE_VERSION_ONE_UNIVERSES: VERSION_ONE,
    BASE_VERSION_TWO: VERSION_TWO
}